# Generated by Django 3.2.2 on 2021-05-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterEntry', '0003_auto_20210511_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfOwnerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turfowner_name', models.CharField(max_length=20)),
                ('turfowner_contact', models.CharField(max_length=20, unique=True)),
                ('turfowner_email', models.EmailField(max_length=20, unique=True)),
                ('turfowner_gender', models.CharField(max_length=20)),
                ('turfowner_address', models.TextField()),
                ('turfowner_image', models.FileField(upload_to='OwnerImage/')),
                ('turfowner_username', models.CharField(max_length=20, unique=True)),
                ('turfowner_password', models.CharField(max_length=20, unique=True)),
                ('turfowner_doj', models.DateField(auto_now_add=True)),
                ('turfowner_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.district', verbose_name='District')),
            ],
        ),
    ]
