# Generated by Django 3.2.2 on 2021-05-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('MasterEntry', '0003_auto_20210511_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfManagerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turfManager_name', models.CharField(max_length=20)),
                ('turfManager_contact', models.CharField(max_length=20, unique=True)),
                ('turfManager_email', models.EmailField(max_length=20, unique=True)),
                ('turfManager_gender', models.CharField(max_length=20)),
                ('turfManager_address', models.TextField()),
                ('turfManager_image', models.FileField(upload_to='ManagerImage/')),
                ('turfManager_username', models.CharField(max_length=20, unique=True)),
                ('turfManager_password', models.CharField(max_length=20, unique=True)),
                ('turfManager_doj', models.DateField(auto_now_add=True)),
                ('turfManager_isactive', models.BooleanField(default=True)),
                ('turfManager_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.district', verbose_name='District')),
                ('turfManager_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.turfownerregistration', verbose_name='Owner')),
            ],
        ),
    ]
