# Generated by Django 3.2.2 on 2021-05-11 06:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')], verbose_name='District:'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')], verbose_name='District:')),
                ('place_District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.district')),
            ],
        ),
    ]
